services:
  postgres:
    image: postgres:14
    container_name: n8n_postgres
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: admin123   # 👉 cámbialo
      POSTGRES_DB: n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=admin123
      - GENERIC_TIMEZONE=America/La_Paz
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=erick123          # 👉 cámbialo
      - N8N_BASIC_AUTH_PASSWORD=Lopezc845     # 👉 cámbialo
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres
  backup:
    image: postgres:14
    container_name: n8n_backup
    depends_on:
      - postgres
    volumes:
      - ./backups:/backups
    entrypoint: >
      sh -c "while true;
      do
        FILENAME=/backups/n8n_backup_$(date +%F_%H-%M-%S).sql;
        PGPASSWORD=n8npass123 pg_dump -h postgres -U n8n n8n > $FILENAME;
        echo '✅ Backup realizado:' $FILENAME;
        # Mantener solo backups de los últimos 7 días
        find /backups -type f -name 'n8n_backup_*.sql' -mtime +7 -exec rm {} \;;
        echo '🧹 Backups antiguos eliminados a las' $(date);
        sleep 86400;
      done"